name: Build and Deploy Static Mkdocs Documentation

# Controls when the action will run. Triggers the workflow on pull request
on:
  push:
    branches:
      - main
    paths:
      - 'mkdocs.yml'
      - 'src/schema/*.yaml'
      - 'src/docs/*'

  repository_dispatch:
    types: trigger-build-deploy-documentation

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      
      # Install pipenv
      - name: Install pipenv
        run: python3 -m pip install --no-cache-dir pipenv
      
      # Load pipenv virtual environment from cache
      # see: https://ianwhitestone.work/aws-serverless-deployments-with-github-actions/
#       - name: Load pipenv from cache
#         uses: actions/cache@v2
#         with:
#           path: ~/.local/share/virtualenvs
#           key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-pipenv-${{ hashFiles('Pipfile.lock') }}


      # If cache was not loaded, install dependencies
      - name: Install dependencies
        run: pipenv install
#         if: steps.cache-pipenv.outputs.cache-hit != 'true'
#         run: pipenv install -d
        
      # install dependencies (use pipenv instead)
      # - run: pip install --upgrade pip
      # - run: pip install mkdocs
      # - run: pip install linkml
        
      # generate markdown files
      - run: make stage-docs

      # deploy documentation (note: requires documentation is in docs dir)
      - run: make gh-deploy
